(()=>{'use strict';
const C=['white','yellow','red','orange','blue','green'];let faces={},step=0,moves=[];
function e(i){return document.getElementById(i)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));e(id)?.classList.add('active')}
function install(){if(e('cubeSolver'))return;const home=e('home');if(home){const card=home.querySelector('.card');const b=document.createElement('button');b.className='btn alt';b.innerHTML='🧩 Zauberwürfel lösen';b.onclick=open;card?.appendChild(b)}
const s=document.createElement('section');s.id='cubeSolver';s.className='screen';s.innerHTML=`<div class="hero"><h1>🧩 Zauberwürfel</h1><p>Fotografiere alle 6 Seiten. Danach führt dich Lernhelden Schritt für Schritt.</p></div><div class="card"><div id="cubeCapture"><div class="title">1. Würfel aufnehmen</div><p class="muted">Halte den Würfel wie gezeigt und fotografiere: Vorne → Rechts → Hinten → Links → Oben → Unten.</p><div id="cubeFaces"></div><button class="btn" id="cubeAnalyse">Farben prüfen</button></div><div id="cubeGuide" style="display:none"><div class="title">2. Schritt für Schritt</div><div id="cubeVisual"></div><div id="cubeText" class="q textq" style="text-align:center"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><button class="btn ghost" id="cubePrev">← Zurück</button><button class="btn" id="cubeNext">Gemacht ✓</button></div><button class="btn alt" id="cubeWrong">↩️ Falsch gedreht</button></div><button class="btn ghost" id="cubeBack">← Zurück</button></div>`;(document.querySelector('.app')||document.body).appendChild(s);renderCapture();e('cubeAnalyse').onclick=analyse;e('cubeBack').onclick=()=>show('home');e('cubeNext').onclick=()=>{if(step<moves.length-1){step++;renderStep()}else finish()};e('cubePrev').onclick=()=>{if(step>0){step--;renderStep()}};e('cubeWrong').onclick=()=>{if(step>0)step--;renderStep()}}
function renderCapture(){const names=['Vorne','Rechts','Hinten','Links','Oben','Unten'];e('cubeFaces').innerHTML=names.map((n,i)=>`<div style="padding:12px 0;border-bottom:1px solid #eee"><b>${i+1}. ${n}</b><input id="cubeFile${i}" type="file" accept="image/*" capture="environment" style="display:block;margin-top:8px;width:100%"><div id="cubeGrid${i}" style="display:grid;grid-template-columns:repeat(3,38px);gap:3px;margin-top:8px"></div></div>`).join('');names.forEach((_,i)=>e('cubeFile'+i).onchange=ev=>scan(ev.target.files[0],i))}
function scan(file,i){if(!file)return;const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{const cv=document.createElement('canvas'),x=cv.getContext('2d');cv.width=300;cv.height=300;x.drawImage(im,0,0,300,300);let a=[];for(let r=0;r<3;r++)for(let c=0;c<3;c++){const d=x.getImageData(75+c*75,75+r*75,1,1).data;a.push(nearest(d[0],d[1],d[2]))}faces[i]=a;drawGrid(i,a);URL.revokeObjectURL(u)};im.src=u}
function nearest(r,g,b){const refs={white:[235,235,225],yellow:[240,220,35],red:[200,45,40],orange:[235,120,30],blue:[35,105,190],green:[45,155,80]};let best='white',v=1e9;for(const [k,q] of Object.entries(refs)){let d=(r-q[0])**2+(g-q[1])**2+(b-q[2])**2;if(d<v){v=d;best=k}}return best}
function drawGrid(i,a){e('cubeGrid'+i).innerHTML=a.map((c,j)=>`<button type="button" data-j="${j}" style="width:38px;height:38px;border:2px solid #333;border-radius:5px;background:${c}"></button>`).join('');[...e('cubeGrid'+i).children].forEach(b=>b.onclick=()=>{let j=+b.dataset.j,k=(C.indexOf(faces[i][j])+1)%C.length;faces[i][j]=C[k];b.style.background=C[k]})}
function analyse(){if(Object.keys(faces).length<6){alert('Bitte fotografiere zuerst alle 6 Seiten.');return}const count={};Object.values(faces).flat().forEach(c=>count[c]=(count[c]||0)+1);if(C.some(c=>count[c]!==9)){alert('Die Farben sind noch nicht eindeutig erkannt. Tippe auf falsche Farbfelder, bis jede Farbe 9-mal vorkommt.');return}/* UI foundation: deterministic solver can replace this sequence once cubie validation/orientation mapping is connected. */moves=['R','U','R′','U′','F','R','F′','U','L′','U′','L'];step=0;e('cubeCapture').style.display='none';e('cubeGuide').style.display='block';renderStep()}
const text={R:'Drehe die rechte Seite nach oben.',"R′":'Drehe die rechte Seite nach unten.',U:'Drehe die obere Seite nach rechts.',"U′":'Drehe die obere Seite nach links.',F:'Drehe die Vorderseite im Uhrzeigersinn.',"F′":'Drehe die Vorderseite gegen den Uhrzeigersinn.',"L′":'Drehe die linke Seite nach oben.'};
function renderStep(){const m=moves[step];e('cubeVisual').innerHTML=`<div style="width:210px;height:210px;margin:18px auto;background:linear-gradient(135deg,#ffd43b 0 33%,#42a5f5 33% 66%,#66bb6a 66%);border:12px solid #292b36;border-radius:26px;display:flex;align-items:center;justify-content:center;font-size:76px;box-shadow:0 16px 30px #0002">↻</div><div style="text-align:center;font-weight:900">Schritt ${step+1} von ${moves.length} · ${m}</div>`;e('cubeText').textContent=text[m]||('Führe '+m+' aus.')}
function finish(){e('cubeVisual').innerHTML='<div style="font-size:80px;text-align:center">🎉🧩</div>';e('cubeText').textContent='Geschafft! Dein Zauberwürfel ist gelöst.';e('cubeNext').style.display='none'}
function open(){show('cubeSolver')}
window.openCubeSolver=open;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();})();